name: Conda CI

on: [push, pull_request]

jobs:
  setup-conda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: myenv
          environment-file: environment.yml
          auto-activate-base: false

      - name: Verify environment
        run: |
          conda info --envs
          which python
          python -c "import numpy, pandas; print('Dependencies work!')"
